### ISSUE TITLE
Task 1

### ISSUE THREAD

**Issue by emadmasri40** [emadmasri40/ASUMobiCarG39#1]
Task 1

We need a program by using Atmel Studio

1- IC No. (ATmega16)

2- Frequency of 1MHZ

3- Assign PA0 & PA1 to work as an output

4- Assign PA5 to work as an input

5- Make a condition PA5 =1 to work PA0 & PA1

6- Make a 100ms delay

Deadline is on saturday 17/2 in the evening..

Upload the code here

**Comment by emadmasri40** [comment]
لي يخلص الكود يحطه هنا

**Comment by TasneemTarek** [comment]
#define F_CPU 1000000UL
#include <avr/io.h>
#include <avr/delay.h>

int main(void)
{
	DDRA = 0b00000011;
    while(1)
    {
     if (PINA == 0b00010000)
	 {PORTA = 0b00000011;
		 _delay_ms(100);}
		 else
		 {PORTA = 0b00000000;} 
    }
}

**Comment by omarmustafa203** [comment]
#define F_CPU 1000000UL
#include <avr/io.h>
#include <util/delay.h>

int main(void)
{
	DDRA=0b00000011;
	while (1)
	{
		
		if(PINB == (1<<PB5)){
			PORTA=0b00000001;
			_delay_ms(1000);
			PORTA=0b00000010;
			_delay_ms(1000);
		}
		if(PINB == (0<<PB5)) {PORTA=0b00000000;_delay_ms(1000);}
	}
}
![default](https://user-images.githubusercontent.com/36368960/36342126-55414e3e-1402-11e8-88e5-e9589610333b.JPG)

**Comment by emadmasri40** [comment]
الناس الي لسا مرفعتش التاسك 
هقفله اساعه 11.30

**Comment by emadmasri40** [comment]
هيتفتح تاني بس مع اضافه بعد الحاجات البسيطه
interrupt 
وشكرا

**Comment by emadmasri40** [comment]
Time has ended

**Comment by hosseldin** [comment]
#define F_CPU 1000000UL
#include <avr/io.h>
#include <avr/delay.h>


int main()
{
	DDRA= 0b00000011;
	
	while(1)
	{
		if(PINA == (1==PA5))
		{
			
		
		PORTA = 0b00000011;       
		 _delay_ms(100);   
		PORTA = 0b00000000;       //turn LED on
		 _delay_ms(100);
		}
		else if(PINA == (0==PA5))
		{
			PORTA = 0b00000000;
			 _delay_ms(100);
		}
	}
	
	return 0;
![tsk1](https://user-images.githubusercontent.com/36197508/36346217-ef75dd18-1442-11e8-9baa-b37a831b0c18.png)

**Comment by RemonRefaat** [comment]
#define F_CPU 1000000UL
#include <avr/io.h>
#include <util/delay.h>
int main(void)
{
   DDRA = 0b00000011;
   while("PORTA = 0b00010000")
   {
	   PORTA = 0b00000011;
	   _delay_ms(100);
   }
   return 0 ;
}
