### ISSUE TITLE
The Design and Implementation 

### ISSUE THREAD

**Issue by omarmustafa203** [emadmasri40/ASUMobiCarG39#10]
This task requires to: 
(1) design the car with ((AVR)) on the simulation. 
(2) design the the mechanical system of the car
(3) collect the tools and car parts and connecting them together

**Comment by emadmasri40** [comment]
ياله يا عصام نزل كل حاجه خاصه بالديزين هنا

**Comment by emadmasri40** [comment]
![image](https://user-images.githubusercontent.com/36333914/36495102-df8179ec-173c-11e8-945d-e993d83c238a.png)

عاوزين نشتخدم دي

**Comment by emadmasri40** [comment]
![image](https://user-images.githubusercontent.com/36333914/36495178-20c0be7c-173d-11e8-85ff-0832891ffb73.png)
او دي

**Comment by emadmasri40** [comment]
no of voltage regulator smd
  SMD "AMS1117-5V"

**Comment by 1essam** [comment]
هنستخدم الى عند رام 
[http://ram-e-shop.com/oscmax/catalog/advanced_search_result.php?keywords=Stackable+Pin&x=0&y=0](url)

**Comment by emadmasri40** [comment]
الناس عاوزه الكبير

**Comment by emadmasri40** [comment]
الموقع مش بيفتح حط صوره لي

**Comment by 1essam** [comment]
![stackable pin header](https://user-images.githubusercontent.com/36341284/36584237-89fa5ab6-1881-11e8-9a6f-e5adb8d5510f.PNG)

**Comment by 1essam** [comment]
i will use 2 MHK 
![crystal](https://user-images.githubusercontent.com/36341284/36584411-43d927fa-1882-11e8-9628-1de7175ddbfa.PNG)

**Comment by emadmasri40** [comment]
هتخلص الديزين امتا

**Comment by emadmasri40** [comment]
هتعرف تخلصه قبل يوم الاحد؟!!!

**Comment by 1essam** [comment]
![captur](https://user-images.githubusercontent.com/36341284/36614563-d0fc162a-18e5-11e8-98cd-5cd9d690e4de.PNG)

**Comment by emadmasri40** [comment]
ic 2560

**Comment by 1essam** [comment]
![dd](https://user-images.githubusercontent.com/36341284/36623630-04e8afe2-190f-11e8-84e9-7e84bf7a723f.PNG)
![new-pcb2](https://user-images.githubusercontent.com/36341284/36623639-118cf8fc-190f-11e8-8da7-bd9844b74772.png)
![ph](https://user-images.githubusercontent.com/36341284/36623644-1c22e4fc-190f-11e8-8846-a07e6b4f3abd.PNG)

**Comment by 1essam** [comment]
![captu](https://user-images.githubusercontent.com/36341284/36623668-4ffc9700-190f-11e8-8c11-ae0e4434ddca.PNG)

**Comment by 1essam** [comment]
[New-PCB2.pdf](https://github.com/emadmasri40/ASUMobiCarG39/files/1753680/New-PCB2.pdf)

**Comment by 1essam** [comment]
last update


![new-pcb-3](https://user-images.githubusercontent.com/36341284/36646598-049972dc-1a82-11e8-80f1-863a875c986a.png)
[New-PCB-3.pdf](https://github.com/emadmasri40/ASUMobiCarG39/files/1756705/New-PCB-3.pdf)

![capture0](https://user-images.githubusercontent.com/36341284/36646579-f2ed5c1a-1a81-11e8-837c-e8d85b95002b.PNG)
![capture4](https://user-images.githubusercontent.com/36341284/36646581-f857b452-1a81-11e8-8490-fd256b7bbc28.PNG)

**Comment by 1essam** [comment]
**_last update_**
![capture0](https://user-images.githubusercontent.com/36341284/36891300-cca715ec-1e09-11e8-94b3-4db5c72014b4.PNG)
![new-pcb-3 1](https://user-images.githubusercontent.com/36341284/36891305-d1f1c9de-1e09-11e8-9a19-c8088106d4fc.png)
[New-PCB-3 (1).pdf](https://github.com/emadmasri40/ASUMobiCarG39/files/1774361/New-PCB-3.1.pdf)

![capture1](https://user-images.githubusercontent.com/36341284/36891271-b000e800-1e09-11e8-85aa-1c01f9b0bc32.PNG)
