### ISSUE TITLE
Task 3

### ISSUE THREAD

**Issue by omarmustafa203** [emadmasri40/ASUMobiCarG39#11]
The objective of Task 3 is making every member of the team work on AVR even those who will not be working on AVR in the CAR_PROJECT.

 Task 3 consists of 3 levels : 
- FIRST LEVEL : 
Create a function that does summing operation of two numbers.
each number is unsigned 8 bits i.e(0 =>255) .
the function must be in form sum(A,B).
the result will appear as LEDs in simulation .
- SECOND LEVEL : 
Create function that does subtracting operation of two numbers.
each number is unsigned 8 bits i.e(0 =>255) .
the function must be in the form sub(A,B).
the function support a negative result.
the result will appear as LEDs in simulation .
- THIRD LEVEL : 
create function that does AND,OR,NOT operations .
 each number is unsigned 8 bits i.e(0 =>255) .
the function must be in the form AND(A,B),OR(A,B),NOT(A).
the result will appear as LEDs in simulation .

some instructions : 
- you can use a calculator to convert from decimal to binary and vise versa.
- you ((CAN"T)) use any functions that already exists in C like ( | , & , ^ ) .
- code must be short as possible. 
- you don't have to solve all levels (at least one level).
- all three levels must be in one program.
- each member must upload solution in his own folder.
- the code in ( c & hex ) forms and the simulation in (pdsprj) form.
- some examples will upload in an other post.
- the Deadline will be on Monday 5/3/2018 at 11:59 PM.

Good Luck.

**Comment by omarmustafa203** [comment]
- Summing operation example .
sum(18,15) =>18+15=(33)in decimal==(00100001) in binary.
the result will appear on simulation as shown.
![level 1](https://user-images.githubusercontent.com/36368960/36645022-6135c1e2-1a6b-11e8-882c-cc2efc59083d.JPG)

**Comment by omarmustafa203** [comment]
- Subtracting operation example(1) .
sub(18,15) =>18-15=(3)in decimal==(00000011) in binary.
the result will appear on simulation as shown.
![level21](https://user-images.githubusercontent.com/36368960/36645024-6d5b74b2-1a6b-11e8-87be-27d70a2f36f6.JPG)

**Comment by omarmustafa203** [comment]
- Subtracting operation example(2) .
sub(5,10) =>5-10=(-5)in decimal==(11111011) in binary.
the result will appear on simulation as shown.
![level22](https://user-images.githubusercontent.com/36368960/36645028-75adaa04-1a6b-11e8-8064-3e12cbf81963.JPG)

**Comment by omarmustafa203** [comment]
- OR operation example .
OR(18,15) 
15     =>00001111
18     =>00010010
result=>00011111
the result will appear on simulation as shown.
![level31](https://user-images.githubusercontent.com/36368960/36645033-80fac964-1a6b-11e8-827d-3d53ff1872ce.JPG)

**Comment by omarmustafa203** [comment]
- AND operation example .
OR(18,15) 
15     =>00001111
18     =>00010010
result=>00000010
the result will appear on simulation as shown.
![level32](https://user-images.githubusercontent.com/36368960/36645037-8c54e308-1a6b-11e8-83b2-9c2bfc01b0c1.JPG)

**Comment by omarmustafa203** [comment]
- NOT operation example .
NOT(18) 
18     =>00010010
result=>11101101
the result will appear on simulation as show
![level33](https://user-images.githubusercontent.com/36368960/36645040-94a2e99c-1a6b-11e8-848c-98f6854c534f.JPG)

**Comment by emadmasri40** [comment]
I am finished of the task
solution 
2 method

**Comment by emadmasri40** [comment]
* Author : Emad masri 
 */
#define F_CPU 1000000UL
#include <avr/io.h>

void convert (uint8_t m ,uint8_t *a)
{
	uint8_t i,n;
	n=m;
	for (i=0;n>0;i++)
	{
		a[i]=n%2;
		n=n/2;
	}
	
}
void op(uint8_t A, uint8_t B, char OP)
{
	uint8_t a[8];
	uint8_t b[8];
	convert(B,b);
	convert(A,a );
	if (OP=='+')
	{
		PORTA=A+B;
	}
	if (OP=='|')
	{
		for (int i=0;i<9;i++)
		{
			if (a[i]==1|b[i]==1)
			{
				PORTA|=(1<<i);
			}
		}
	}
		if (OP=='&')
		{
			for (int i=0;i<9;i++)
			{
				if (a[i]==1&b[i]==1)
				{
					PORTA|=(1<<i);
				}
		}
	}
	if (OP=='-')
	{
		uint8_t f;
		f=255-B;
		PORTA=A+f+1;
	}
}
int main(void)
{
	DDRA=0xff;
uint8_t n=5,m=9,a[8];

    /* Replace with your application code */
    while (1) 
    {
		op(n,m,'-');//n first number m second number char OP( + OR - OR & OR | )
			
		}
		
}

**Comment by hosseldin** [comment]
#include <avr/io.h>
#include <avr/delay.h>


uint8_t sum(uint8_t a, uint8_t b)
{
	return a+b;
}

uint8_t sub(uint8_t a, uint8_t b)
{
	return a-b;
}





int main(void)
{
   int a=5, b=7;
    DDRA = 0xff;
	
	while (1)
	{
		
	}

	return 0;

}
