### ISSUE TITLE
Interfacing an HC-SR04 Ultrasonic Sensor with AVR Microcontroller

### ISSUE THREAD

**Issue by hosseldin** [emadmasri40/ASUMobiCarG39#12]
In this part we will program the ultrasonic sensor which is a device that can measure the distance to an object by using sound waves. It measures distance by sending out a sound wave at a specific frequency and listening for that sound wave to bounce back. By recording the elapsed time between the sound wave being generated and the sound wave bouncing back, it is possible to calculate the distance between the sonar sensor and the object.
Distance = (speed of sound x time taken )/ 2Since it is known that sound travels through air at about 344 m/s (1129 ft/s), you can take the time for the sound wave to return and multiply it by 344 meters (or 1129 feet) to find the total round-trip distance of the sound wave. Round-trip means that the sound wave traveled 2 times the distance to the object before it was detected by the sensor; it includes the 'trip' from the sonar sensor to the object AND the 'trip' from the object to the Ultrasonic sensor (after the sound wave bounced off the object). To find the distance to the object, simply divide the round-trip distance in half.

**Comment by sanody** [comment]
![ult 1](https://user-images.githubusercontent.com/36520315/37313288-3ad88c08-2657-11e8-8504-150ff204625c.png)

**Comment by sanody** [comment]
![ult 2](https://user-images.githubusercontent.com/36520315/37313363-8961496e-2657-11e8-94c5-c1b138d6e310.png)
