### ISSUE TITLE
Sheet 1 Assignment

### ISSUE THREAD

**Issue by omarmustafa203** [emadmasri40/ASUMobiCarG39#5]
[Sheet 1.pdf](https://github.com/emadmasri40/ASUMobiCarG39/files/1737963/Sheet.1.pdf)

**Comment by omarmustafa203** [comment]
its required to upload solution (code and and simulation ) on the folder of each member.

**Comment by emadmasri40** [comment]
عملت لكل واحد فولدر باسم 
sheet solution

**Comment by emadmasri40** [comment]
انا حليت الشيت #

**Comment by RemonRefaat** [comment]
Done #

**Comment by nadahamdy98** [comment]
![screenshot 2](https://user-images.githubusercontent.com/36543116/36624978-1e07dc0a-1928-11e8-8193-6e896005d6ca.png)

**Comment by nadahamdy98** [comment]
![screenshot 3](https://user-images.githubusercontent.com/36543116/36625014-c47d7dc4-1928-11e8-9081-f99a74e0e3f6.png)

**Comment by nadahamdy98** [comment]
![screenshot 4](https://user-images.githubusercontent.com/36543116/36625021-e087293e-1928-11e8-9957-3421e4b51060.png)

**Comment by nadahamdy98** [comment]
what is the problem here ?? 
the code build with no errors and I checked the wires and connections on proteus many times 
and checked my steps from AVR book (pdf) w msh 3rfa al moshkla fan brdo :'''')
