### ISSUE TITLE
Solution of Sheet 1 Assignment  

### ISSUE THREAD

**Issue by emadmasri40** [emadmasri40/ASUMobiCarG39#7]
correct the mistakes in the solution sheet

**Comment by emadmasri40** [comment]
الناس ترفع الحول هنا لو سمحت

**Comment by hosseldin** [comment]
// Q2

#define F_CPU 1000000UL
#include <avr/io.h>
#include <avr/delay.h>


int main()
{
	DDRA= 0b00001111;
	
	while(1)
	{
	
		PORTA = 0b00000001;       
		 _delay_ms(1000);   
		PORTA = 0b00000010;       //turn LED on
		 _delay_ms(1000);
		PORTA = 0b00000100;       //turn LED on
		 _delay_ms(1000);
		PORTA = 0b00001000;       //turn LED on
		 _delay_ms(1000);
	}
		return 0;
}

**Comment by emadmasri40** [comment]
زود عليه انه يقفل بقا

**Comment by emadmasri40** [comment]
و حطه في الفولدر بتاعك

**Comment by hosseldin** [comment]
قصدك ايه ب يقفل؟

**Comment by emadmasri40** [comment]
turn off

**Comment by hosseldin** [comment]
يا شيخ

**Comment by emadmasri40** [comment]
اه اوللهي

**Comment by emadmasri40** [comment]
portA=0;

**Comment by omarmustafa203** [comment]
int main(void)
{
	DDRA=0b00001111;
    while (1) 
    {
		for(int i=1;i<=8;i=i*2  ){
			PORTA=i;
	_delay_ms(1000);}
		PORTA=0;
		_delay_ms(250);
		for(int i=8;i>=1;i=i/2  ){
			PORTA=i;
			_delay_ms(1000);}
		PORTA=0;
		_delay_ms(250);}
}

**Comment by emadmasri40** [comment]
ممكن شرح الكود في السريع او تكتب ايه الي كان مطلوب في الشيت علشان لو حد دخل يفهم احنا كنا عاوزين نعمل ايه

**Comment by omarmustafa203** [comment]
حسام انت عامل الليدات بتنور في اتجاه واحد

**Comment by omarmustafa203** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/36368960/36594005-06f2fdc0-18a5-11e8-8b43-cf087134ed63.gif)

**Comment by emadmasri40** [comment]
#define F_CPU 1000000UL

#include <avr/io.h>
#include <util/delay.h>
int main  ( )
{
// Input/Output Ports initialization
	// Port A initialization
	// Function: Bit7=Out Bit6=Out Bit5=Out Bit4=Out Bit3=In Bit2=In Bit1=In Bit0=In
	DDRA=(1<<DDA7) | (1<<DDA6) | (1<<DDA5) | (1<<DDA4) | (0<<DDA3) | (0<<DDA2) | (0<<DDA1) | (0<<DDA0);
	// State: Bit7=0 Bit6=0 Bit5=0 Bit4=0 Bit3=T Bit2=T Bit1=T Bit0=T
	PORTA=(0<<PORTA7) | (0<<PORTA6) | (0<<PORTA5) | (0<<PORTA4) | (0<<PORTA3) | (0<<PORTA2)     | (0<<PORTA1) | (0<<PORTA0);
while (1)
	{
		//_delay_ms(200);
		int d,m;
		for (int i=4;i<8;i++)
		{
			d=PA0+i;
			PORTA|=(1<<d);
			_delay_ms(520);
		}
		for (int i=0;i<5;i++)
		{
			m=d-i;
			PORTA &=~(1<<m);
			_delay_ms(520);
		}
	}
}
