### ISSUE TITLE
Motors

### ISSUE THREAD

**Issue by emadmasri40** [emadmasri40/ASUMobiCarG39#8]
L293D(motor driver ) AVR motor connection

**Comment by emadmasri40** [comment]
اولا الاي سي ده شغال بي حاجه اسمها 
PWM – Pulse Width Modulation
علشان اشغله في اي سي 
لازم نظبط الريجستر بتاعتهم 
- [TCCR0 ] 
ده جواه ال الاسامي دي 
Name | FOC0 | WGM00 | COM01 | COM00 | WGM01 | CS02 | CS01 | CS00

**Comment by emadmasri40** [comment]
![screenshot_1](https://user-images.githubusercontent.com/36333914/36494501-dd6bca2e-173a-11e8-9fef-d94f4b2968e8.png)

**Comment by emadmasri40** [comment]
![image](https://user-images.githubusercontent.com/36333914/36494543-f7ba125a-173a-11e8-8af7-c91e261c4f26.png)

**Comment by emadmasri40** [comment]
![image](https://user-images.githubusercontent.com/36333914/36494575-122aa7a8-173b-11e8-8a91-23f265a33e89.png)

**Comment by emadmasri40** [comment]
![image](https://user-images.githubusercontent.com/36333914/36495463-f128d996-173d-11e8-9103-08c347c3e8ed.png)

**Comment by emadmasri40** [comment]
وصلته لحد فين

**Comment by omarmustafa203** [comment]
![default](https://user-images.githubusercontent.com/36368960/36643498-dc370d68-1a54-11e8-8ec5-b6540be20033.JPG)

**Comment by omarmustafa203** [comment]
How servo motor works : 

- servo motor must operating at 50Hz frequency square signal .
-  the angle that servo make is direct proportional to duty cycle of signal.
- to make (-90 degree) duty cycle must be .5% i.e ( HIGH for 1ms)
to make (90 degree) duty cycle must be 2% i.e ( HIGH for 2ms) and so on.

**Comment by omarmustafa203** [comment]
16-bit timer 
![compare output mode fast pwm](https://user-images.githubusercontent.com/36368960/36644870-06f0b66c-1a69-11e8-8d19-c6ac990b1a4d.JPG)
